// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfwXnFP2vIzIumX7yptu7HZlLZVqJGk70',
    appId: '1:1032740027042:web:b4a10ac631d0bb58df35fb',
    messagingSenderId: '1032740027042',
    projectId: 'quan-li-thu-chi-c2cdd',
    authDomain: 'quan-li-thu-chi-c2cdd.firebaseapp.com',
    storageBucket: 'quan-li-thu-chi-c2cdd.firebasestorage.app',
    measurementId: 'G-VR4YWG6T4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJuTbTnaxyzHMTV7yWez5owd5wlt6wZcM',
    appId: '1:1032740027042:android:e8439e81a93676a7df35fb',
    messagingSenderId: '1032740027042',
    projectId: 'quan-li-thu-chi-c2cdd',
    storageBucket: 'quan-li-thu-chi-c2cdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc-ImKnfIA_XcoxMZOWiRy9ZfyMrr8vbg',
    appId: '1:1032740027042:ios:7a0218c7ffbb5c09df35fb',
    messagingSenderId: '1032740027042',
    projectId: 'quan-li-thu-chi-c2cdd',
    storageBucket: 'quan-li-thu-chi-c2cdd.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChiTieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc-ImKnfIA_XcoxMZOWiRy9ZfyMrr8vbg',
    appId: '1:1032740027042:ios:7a0218c7ffbb5c09df35fb',
    messagingSenderId: '1032740027042',
    projectId: 'quan-li-thu-chi-c2cdd',
    storageBucket: 'quan-li-thu-chi-c2cdd.firebasestorage.app',
    iosBundleId: 'com.example.quanLyChiTieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfwXnFP2vIzIumX7yptu7HZlLZVqJGk70',
    appId: '1:1032740027042:web:c20dd3ed13804468df35fb',
    messagingSenderId: '1032740027042',
    projectId: 'quan-li-thu-chi-c2cdd',
    authDomain: 'quan-li-thu-chi-c2cdd.firebaseapp.com',
    storageBucket: 'quan-li-thu-chi-c2cdd.firebasestorage.app',
    measurementId: 'G-KQH2JJ5XYM',
  );
}
